/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// CharacterType : type of a character 角色，机体，舰船，组织...
/// type of a character 角色，机体，舰船，组织...
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum CharacterType {
    Character = 1,
    Mechanic = 2,
    Ship = 3,
    Organization = 4,

}

impl std::fmt::Display for CharacterType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Character => "1",
            Self::Mechanic => "2",
            Self::Ship => "3",
            Self::Organization => "4",
        })
    }
}
impl Default for CharacterType {
    fn default() -> CharacterType {
        Self::Character
    }
}

