/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collection {
    #[serde(rename = "wish")]
    pub wish: i32,
    #[serde(rename = "collect")]
    pub collect: i32,
    #[serde(rename = "doing")]
    pub doing: i32,
    #[serde(rename = "on_hold")]
    pub on_hold: i32,
    #[serde(rename = "dropped")]
    pub dropped: i32,
}

impl Collection {
    pub fn new(wish: i32, collect: i32, doing: i32, on_hold: i32, dropped: i32) -> Collection {
        Collection {
            wish,
            collect,
            doing,
            on_hold,
            dropped,
        }
    }
}

