/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Count {
    #[serde(rename = "1", skip_serializing_if = "Option::is_none")]
    pub param_1: Option<i32>,
    #[serde(rename = "2", skip_serializing_if = "Option::is_none")]
    pub param_2: Option<i32>,
    #[serde(rename = "3", skip_serializing_if = "Option::is_none")]
    pub param_3: Option<i32>,
    #[serde(rename = "4", skip_serializing_if = "Option::is_none")]
    pub param_4: Option<i32>,
    #[serde(rename = "5", skip_serializing_if = "Option::is_none")]
    pub param_5: Option<i32>,
    #[serde(rename = "6", skip_serializing_if = "Option::is_none")]
    pub param_6: Option<i32>,
    #[serde(rename = "7", skip_serializing_if = "Option::is_none")]
    pub param_7: Option<i32>,
    #[serde(rename = "8", skip_serializing_if = "Option::is_none")]
    pub param_8: Option<i32>,
    #[serde(rename = "9", skip_serializing_if = "Option::is_none")]
    pub param_9: Option<i32>,
    #[serde(rename = "10", skip_serializing_if = "Option::is_none")]
    pub param_10: Option<i32>,
}

impl Count {
    pub fn new() -> Count {
        Count {
            param_1: None,
            param_2: None,
            param_3: None,
            param_4: None,
            param_5: None,
            param_6: None,
            param_7: None,
            param_8: None,
            param_9: None,
            param_10: None,
        }
    }
}

