/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// EpisodeCollectionType : - `0`: 未收藏 - `1`: 想看 - `2`: 看过 - `3`: 抛弃
/// - `0`: 未收藏 - `1`: 想看 - `2`: 看过 - `3`: 抛弃
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum EpisodeCollectionType {
    Variant1 = 1,
    Variant2 = 2,
    Variant3 = 3,

}

impl std::fmt::Display for EpisodeCollectionType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::Variant1 => "1",
            Self::Variant2 => "2",
            Self::Variant3 => "3",
        })
    }
}
impl Default for EpisodeCollectionType {
    fn default() -> EpisodeCollectionType {
        Self::Variant1
    }
}

