/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMyself200Response {
    #[serde(rename = "id")]
    pub id: i32,
    /// 唯一用户名，初始与 UID 相同，可修改一次
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "nickname")]
    pub nickname: String,
    #[serde(rename = "user_group")]
    pub user_group: models::UserGroup,
    #[serde(rename = "avatar")]
    pub avatar: Box<models::Avatar>,
    /// 个人签名
    #[serde(rename = "sign")]
    pub sign: String,
    /// 用户绑定的邮箱地址
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// 用户注册时间。比如 2017-12-03T08:51:16+08:00
    #[serde(rename = "reg_time", skip_serializing_if = "Option::is_none")]
    pub reg_time: Option<String>,
    /// 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8
    #[serde(rename = "time_offset", skip_serializing_if = "Option::is_none")]
    pub time_offset: Option<i32>,
}

impl GetMyself200Response {
    pub fn new(id: i32, username: String, nickname: String, user_group: models::UserGroup, avatar: models::Avatar, sign: String) -> GetMyself200Response {
        GetMyself200Response {
            id,
            username,
            nickname,
            user_group,
            avatar: Box::new(avatar),
            sign,
            email: None,
            reg_time: None,
            time_offset: None,
        }
    }
}

