/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Images {
    #[serde(rename = "large")]
    pub large: String,
    #[serde(rename = "common")]
    pub common: String,
    #[serde(rename = "medium")]
    pub medium: String,
    #[serde(rename = "small")]
    pub small: String,
    #[serde(rename = "grid")]
    pub grid: String,
}

impl Images {
    pub fn new(large: String, common: String, medium: String, small: String, grid: String) -> Images {
        Images {
            large,
            common,
            medium,
            small,
            grid,
        }
    }
}

