/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexSubjectEditInfo : 修改目录中条目的信息
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSubjectEditInfo {
    /// 排序条件，越小越靠前
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<i32>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl IndexSubjectEditInfo {
    /// 修改目录中条目的信息
    pub fn new() -> IndexSubjectEditInfo {
        IndexSubjectEditInfo {
            sort: None,
            comment: None,
        }
    }
}

