/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexBasicInfo : 新增或修改条目的内容，同名字段意义同<a href=\"#model-Subject\">Subject</a>
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexBasicInfo {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl IndexBasicInfo {
    /// 新增或修改条目的内容，同名字段意义同<a href=\"#model-Subject\">Subject</a>
    pub fn new() -> IndexBasicInfo {
        IndexBasicInfo {
            title: None,
            description: None,
        }
    }
}

