/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexSubject : 同名字段意义同<a href=\"#model-Subject\">Subject</a>
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSubject {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Box<models::Images>>,
    #[serde(rename = "infobox", skip_serializing_if = "Option::is_none")]
    pub infobox: Option<Vec<models::Item>>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "added_at")]
    pub added_at: String,
}

impl IndexSubject {
    /// 同名字段意义同<a href=\"#model-Subject\">Subject</a>
    pub fn new(id: i32, r#type: i32, name: String, comment: String, added_at: String) -> IndexSubject {
        IndexSubject {
            id,
            r#type,
            name,
            images: None,
            infobox: None,
            date: None,
            comment,
            added_at,
        }
    }
}

