/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Index {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "desc")]
    pub desc: String,
    /// 收录条目总数
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// 目录评论及收藏数
    #[serde(rename = "stat")]
    pub stat: Box<models::Stat>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "creator")]
    pub creator: Box<models::Creator>,
    /// deprecated, always false.
    #[serde(rename = "ban")]
    pub ban: bool,
    #[serde(rename = "nsfw")]
    pub nsfw: bool,
}

impl Index {
    pub fn new(id: i32, title: String, desc: String, stat: models::Stat, created_at: String, updated_at: String, creator: models::Creator, ban: bool, nsfw: bool) -> Index {
        Index {
            id,
            title,
            desc,
            total: None,
            stat: Box::new(stat),
            created_at,
            updated_at,
            creator: Box::new(creator),
            ban,
            nsfw,
        }
    }
}

