/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegacyMonoInfo : 人物信息
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacyMonoInfo {
    /// 生日
    #[serde(rename = "birth", skip_serializing_if = "Option::is_none")]
    pub birth: Option<String>,
    /// 身高
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
    /// 性别
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<Box<models::LegacyMonoInfoAlias>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::LegacyMonoInfoSource>>,
    /// 简体中文名
    #[serde(rename = "name_cn", skip_serializing_if = "Option::is_none")]
    pub name_cn: Option<String>,
    /// 声优
    #[serde(rename = "cv", skip_serializing_if = "Option::is_none")]
    pub cv: Option<String>,
}

impl LegacyMonoInfo {
    /// 人物信息
    pub fn new() -> LegacyMonoInfo {
        LegacyMonoInfo {
            birth: None,
            height: None,
            gender: None,
            alias: None,
            source: None,
            name_cn: None,
            cv: None,
        }
    }
}

