/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegacyBlog : 日志
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacyBlog {
    /// ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// 地址
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// 标题
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// 概览
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// 图片
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// 回复数
    #[serde(rename = "replies", skip_serializing_if = "Option::is_none")]
    pub replies: Option<i32>,
    /// 发布时间
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
    /// 发布时间
    #[serde(rename = "dateline", skip_serializing_if = "Option::is_none")]
    pub dateline: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::LegacyUser>>,
}

impl LegacyBlog {
    /// 日志
    pub fn new() -> LegacyBlog {
        LegacyBlog {
            id: None,
            url: None,
            title: None,
            summary: None,
            image: None,
            replies: None,
            timestamp: None,
            dateline: None,
            user: None,
        }
    }
}

