/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegacyMonoInfoAlias : 别名（另外添加出来的 key 为 0 开始的数字）
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacyMonoInfoAlias {
    /// 日文名
    #[serde(rename = "jp", skip_serializing_if = "Option::is_none")]
    pub jp: Option<String>,
    /// 纯假名
    #[serde(rename = "kana", skip_serializing_if = "Option::is_none")]
    pub kana: Option<String>,
    /// 昵称
    #[serde(rename = "nick", skip_serializing_if = "Option::is_none")]
    pub nick: Option<String>,
    /// 罗马字
    #[serde(rename = "romaji", skip_serializing_if = "Option::is_none")]
    pub romaji: Option<String>,
    /// 第二中文名
    #[serde(rename = "zh", skip_serializing_if = "Option::is_none")]
    pub zh: Option<String>,
}

impl LegacyMonoInfoAlias {
    /// 别名（另外添加出来的 key 为 0 开始的数字）
    pub fn new() -> LegacyMonoInfoAlias {
        LegacyMonoInfoAlias {
            jp: None,
            kana: None,
            nick: None,
            romaji: None,
            zh: None,
        }
    }
}

