/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegacySubjectSmallRating : 评分
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacySubjectSmallRating {
    /// 总评分人数
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<Box<models::LegacySubjectSmallRatingCount>>,
    /// 评分
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f64>,
}

impl LegacySubjectSmallRating {
    /// 评分
    pub fn new() -> LegacySubjectSmallRating {
        LegacySubjectSmallRating {
            total: None,
            count: None,
            score: None,
        }
    }
}

