/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegacyMonoBaseImages : 肖像
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegacyMonoBaseImages {
    #[serde(rename = "large", skip_serializing_if = "Option::is_none")]
    pub large: Option<String>,
    #[serde(rename = "medium", skip_serializing_if = "Option::is_none")]
    pub medium: Option<String>,
    #[serde(rename = "small", skip_serializing_if = "Option::is_none")]
    pub small: Option<String>,
    #[serde(rename = "grid", skip_serializing_if = "Option::is_none")]
    pub grid: Option<String>,
}

impl LegacyMonoBaseImages {
    /// 肖像
    pub fn new() -> LegacyMonoBaseImages {
        LegacyMonoBaseImages {
            large: None,
            medium: None,
            small: None,
            grid: None,
        }
    }
}

