/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonCharacter {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    /// 角色，机体，舰船，组织...
    #[serde(rename = "type")]
    pub r#type: models::CharacterType,
    /// object with some size of images, this object maybe `null`
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Box<models::PersonImages>>,
    #[serde(rename = "subject_id")]
    pub subject_id: i32,
    #[serde(rename = "subject_type")]
    pub subject_type: models::SubjectType,
    #[serde(rename = "subject_name")]
    pub subject_name: String,
    #[serde(rename = "subject_name_cn")]
    pub subject_name_cn: String,
    #[serde(rename = "staff", skip_serializing_if = "Option::is_none")]
    pub staff: Option<String>,
}

impl PersonCharacter {
    pub fn new(id: i32, name: String, r#type: models::CharacterType, subject_id: i32, subject_type: models::SubjectType, subject_name: String, subject_name_cn: String) -> PersonCharacter {
        PersonCharacter {
            id,
            name,
            r#type,
            images: None,
            subject_id,
            subject_type,
            subject_name,
            subject_name_cn,
            staff: None,
        }
    }
}

