/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonRevisionDataItem {
    #[serde(rename = "prsn_infobox")]
    pub prsn_infobox: String,
    #[serde(rename = "prsn_summary")]
    pub prsn_summary: String,
    #[serde(rename = "profession")]
    pub profession: Box<models::PersonRevisionProfession>,
    #[serde(rename = "extra")]
    pub extra: Box<models::RevisionExtra>,
    #[serde(rename = "prsn_name")]
    pub prsn_name: String,
}

impl PersonRevisionDataItem {
    pub fn new(prsn_infobox: String, prsn_summary: String, profession: models::PersonRevisionProfession, extra: models::RevisionExtra, prsn_name: String) -> PersonRevisionDataItem {
        PersonRevisionDataItem {
            prsn_infobox,
            prsn_summary,
            profession: Box::new(profession),
            extra: Box::new(extra),
            prsn_name,
        }
    }
}

