/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectRevision {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "creator", skip_serializing_if = "Option::is_none")]
    pub creator: Option<Box<models::Creator>>,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::SubjectRevisionData>>,
}

impl SubjectRevision {
    pub fn new(id: i32, r#type: i32, summary: String, created_at: String) -> SubjectRevision {
        SubjectRevision {
            id,
            r#type,
            creator: None,
            summary,
            created_at,
            data: None,
        }
    }
}

