/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserEpisodeCollection {
    #[serde(rename = "episode")]
    pub episode: Box<models::Episode>,
    #[serde(rename = "type")]
    pub r#type: models::EpisodeCollectionType,
    /// A int64 unix timestamp, `0` as unknown or un-recorded.
    #[serde(rename = "updated_at")]
    pub updated_at: i32,
}

impl UserEpisodeCollection {
    pub fn new(episode: models::Episode, r#type: models::EpisodeCollectionType, updated_at: i32) -> UserEpisodeCollection {
        UserEpisodeCollection {
            episode: Box::new(episode),
            r#type,
            updated_at,
        }
    }
}

