/*
 * Bangumi API
 *
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-07-1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSubjectCollectionModifyPayload : 所有的字段均可选
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSubjectCollectionModifyPayload {
    /// 修改条目收藏类型
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::SubjectCollectionType>,
    /// 评分，`0` 表示删除评分
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<i32>,
    /// 只能用于修改书籍条目进度
    #[serde(rename = "ep_status", skip_serializing_if = "Option::is_none")]
    pub ep_status: Option<i32>,
    /// 只能用于修改书籍条目进度
    #[serde(rename = "vol_status", skip_serializing_if = "Option::is_none")]
    pub vol_status: Option<i32>,
    /// 评价
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// 仅自己可见
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<bool>,
    /// 不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl UserSubjectCollectionModifyPayload {
    /// 所有的字段均可选
    pub fn new() -> UserSubjectCollectionModifyPayload {
        UserSubjectCollectionModifyPayload {
            r#type: None,
            rate: None,
            ep_status: None,
            vol_status: None,
            comment: None,
            private: None,
            tags: None,
        }
    }
}

